### ISSUE TITLE
how to save model

### ISSUE THREAD

**Issue by zhaoyingjun** [thibo73800/tensorflow2.0-examples#1]
i have tried the api  (tf.keras.models.save_mdoel) of tf-2.0-night to save model ,but it does not work.

**Comment by thibo73800** [comment]
What is your error message ?

**Comment by zhaoyingjun** [comment]
notimplementederror:  model.get_config

**Comment by thibo73800** [comment]
Which notebook gives you this error ?

**Comment by zhaoyingjun** [comment]
no,not notebook,in my code

**Comment by zhaoyingjun** [comment]
there is  no save model in your examples,so can you please tell me the right way to save model in tf2.0

**Comment by zhaoyingjun** [comment]
i find the save mode in tf.keras.Sequential,it is base tf.keras.models.save_model

**Comment by thibo73800** [comment]
There is two example at the end of theses two notebooks: 

https://github.com/thibo73800/tensorflow2.0-examples/blob/master/others/Simple%20neural%20network%20Saved.ipynb

https://github.com/thibo73800/tensorflow2.0-examples/blob/master/RNN%20-%20Text%20Generator.ipynb

**Comment by zhaoyingjun** [comment]
ok thx

**Comment by zhaoyingjun** [comment]
i have a problem,when  i create  a  custom layer,l  save it use model.save or tf.keras.models.save_model,but when i reload it use tf.keras.models.laod_model,it raise ValueError: Unknown layer: MlpLayer.

the notebook is https://github.com/thibo73800/tensorflow2.0-examples/blob/master/Create%20custom%20layer.ipynb

**Comment by thibo73800** [comment]
I just changed the notebook with one example on how to do it.

I have added a **get_config** method to the custom layer, then I have added a new parameter: **custom_objects**  when the saved model is loaded.

**Comment by zhaoyingjun** [comment]
thx very much ,it is work
